name: Java CI with Maven

permissions:
  contents: read

on:
  pull_request:
    branches: ["*"]

jobs:
  call-maven-ci:
    uses: project-ncl/shared-github-actions/.github/workflows/maven-ci.yml@4ce7005f9d9b3be90e606e8a69e5fab884bfe247 # main
    with:
      upload_artifacts: true
