name: Java CI with Maven

permissions:
  contents: read

on:
  pull_request:
    branches: ["*"]

jobs:
  call-maven-ci:
    uses: project-ncl/shared-github-actions/.github/workflows/maven-ci.yml@292cff5496a8a221e20ab9cd82a17e173e926db0 # main
    with:
      upload_artifacts: true
