name: Java CI with Maven

permissions:
  contents: read

on:
  pull_request:
    branches: ["*"]

jobs:
  call-maven-ci:
    uses: project-ncl/shared-github-actions/.github/workflows/maven-ci.yml@899a05924ef8679de84ba6e42ab874885bf48f80 # main
    with:
      upload_artifacts: true
